### ISSUE TITLE
process ended, multiple errors, stuck in a loop

### ISSUE THREAD

**Issue by JazJonFL** [mikeknoop/homebridge-meural#21]
It stopped working for me this week.  I tried to uninstall and reinstall but it still gets stuck in the following loop
Everything else is up to date including nodejs.

`
/var/lib/homebridge/node_modules/homebridge-meural/node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 401
    at createError (/var/lib/homebridge/node_modules/homebridge-meural/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/lib/homebridge/node_modules/homebridge-meural/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-meural/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
[17/09/2024, 17:54:12] [homebridge-meural] Child bridge process ended
[17/09/2024, 17:54:12] [homebridge-meural] Process Ended. Code: 1, Signal: null 
`

**Comment by tritter** [comment]
Same for me, I think that the auth url changed...

**Comment by rpmartinez3** [comment]
Hi, were you able to get it working?

**Comment by JazJonFL** [comment]
I gave up waiting. Looks like this will never be fixed.  I’m turning mine on and off via Aqara smart switches for now.
